services:
  - type: web
    name: social-app-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: social-app-db
          property: connectionString
      # Add these environment variables in Render dashboard:
      # JWT_SECRET: your_jwt_secret_here
      # FIREBASE_PROJECT_ID: push-notifications-test-1317a  
      # FIREBASE_PRIVATE_KEY_ID: your_private_key_id
      # FIREBASE_PRIVATE_KEY: "-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----\n"
      # FIREBASE_CLIENT_EMAIL: your_service_account_email
      # FIREBASE_CLIENT_ID: your_client_id
      # FIREBASE_CLIENT_CERT_URL: your_cert_url
      # VAPID_PUBLIC_KEY: your_vapid_public_key
      # VAPID_PRIVATE_KEY: your_vapid_private_key  
      # VAPID_SUBJECT: mailto:your_email@example.com
      # EMAIL_HOST: smtp.gmail.com
      # EMAIL_PORT: 587
      # EMAIL_USER: your_email@gmail.com
      # EMAIL_PASS: your_app_password
      # CLOUDINARY_CLOUD_NAME: your_cloudinary_name
      # CLOUDINARY_UPLOAD_PRESET: your_upload_preset
      # FRONTEND_URL: https://your-frontend-url.vercel.app
    domains:
      - your-backend-app.onrender.com

databases:
  - name: social-app-db
    databaseName: social_app
    user: admin